### ISSUE TITLE
Add wiki

### ISSUE THREAD

**Issue by Zumbalamambo** [guoxiaolu/facerecognition#4]
how do I use this in realtime recognition?

**Comment by guoxiaolu** [comment]
In fact, this project is under development although the basic architecture is finished. If you're interested, I will introduce it in brief. First, you need a elasticsearch and a plugin for cosine distance calculation, just as README. Then start es, and start server/httpserver.. Finally, start client/get_face_dlib_per3.py, it can detect and recognize face in real time. Unfortunately, the recognition result is not good enough, and we're committed to some improvement.
